name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm install -g firebase-tools

      - run: firebase deploy --only hosting --project hteamxapp-2d851 --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HTEAMXAPP_2D851 }}"
